import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyWorkspace,demoWorkspace,percentage,periodTasks,workspaceSchema,materializeRoutines,removeEntity,achievements,streak,addDays} from '../lib/jarvis.ts';
const today='2026-09-16';
function recurring(){const d=emptyWorkspace();d.routines.push({id:'morning',title:'Estudar',description:'',start:'2026-09-14',end:null,time:'08:00',days:[1,2,3,4,5],active:true,areaId:'estudos',competencyIds:['disciplina'],goalId:null,lastGenerated:null});return d;}
test('PDF example: eight of ten yields 80%; competency denominator is the matching group',()=>{const d=demoWorkspace('Daniel',today);assert.equal(percentage(d.tasks),80);assert.equal(percentage(d.tasks.filter(t=>t.competencyIds.includes('disciplina'))),80);assert.equal(percentage(d.tasks.filter(t=>t.competencyIds.includes('foco'))),80);assert.equal(percentage([]),0);});
test('period boundaries include start and end, and exclude outside deadlines',()=>{const d=demoWorkspace('Daniel',today);d.tasks[0].due=addDays(today,-1);d.tasks[1].due=addDays(today,1);assert.equal(periodTasks(d,today,today).length,8);assert.equal(periodTasks(d,addDays(today,-1),today).length,9);});
test('recurrence is idempotent and separates daily completion',()=>{let d=materializeRoutines(recurring(),today);assert.equal(d.tasks.length,3);d.tasks[0].done=true;d.tasks[0].completedAt=today;d=materializeRoutines(d,today);assert.equal(d.tasks.length,3);d=materializeRoutines(d,addDays(today,1));assert.equal(d.tasks.length,4);assert.equal(d.tasks.at(-1).done,false);assert.equal(d.tasks.filter(t=>t.done).length,1);assert.ok(workspaceSchema.safeParse(d).success);});
test('deleted occurrences stay deleted and deleting a routine preserves task history',()=>{let d=materializeRoutines(recurring(),today);const deletedId=d.tasks[1].id;d=removeEntity(d,'task',deletedId);d.routines[0].lastGenerated=null;d=materializeRoutines(d,today);assert.equal(d.tasks.length,2);assert.ok(!d.tasks.some(t=>t.id===deletedId));d=removeEntity(d,'routine','morning');assert.equal(d.tasks.length,2);assert.ok(d.tasks.every(t=>t.routineId===null));assert.ok(workspaceSchema.safeParse(d).success);});
test('relationships are cleaned atomically when categories and goals are removed',()=>{let d=demoWorkspace('Daniel',today);d=removeEntity(d,'area','estudos');d=removeEntity(d,'competency','disciplina');d=removeEntity(d,'goal','demo-goal');assert.ok(d.tasks.every(t=>t.areaId===null&&t.goalId===null&&!t.competencyIds.includes('disciplina')));assert.ok(workspaceSchema.safeParse(d).success);});
test('invalid dates, orphan references, duplicate IDs and inconsistent completion are rejected',()=>{for(const mutate of [d=>d.tasks[0].due='2026-02-30',d=>d.tasks[0].areaId='missing',d=>d.tasks.push({...d.tasks[0]}),d=>d.tasks[0].completedAt=null,d=>d.tasks[0].competencyIds=['missing']]){const d=demoWorkspace('Daniel',today);mutate(d);assert.equal(workspaceSchema.safeParse(d).success,false);}});
test('consecutive days and achievements derive from real completions and can be reversed',()=>{let d=demoWorkspace('Daniel',today);d.tasks[0].completedAt=addDays(today,-1);d.tasks[1].completedAt=addDays(today,-2);assert.equal(streak(d,today),3);assert.equal(achievements(d,today).find(a=>a.id==='three').current,3);for(const t of d.tasks){t.done=false;t.completedAt=null;}assert.equal(streak(d,today),0);assert.equal(achievements(d,today).find(a=>a.id==='first').current,0);});
test('weekdays, pause and end boundaries do not create unwanted occurrences',()=>{const d=recurring();d.routines[0].end='2026-09-18';const r=materializeRoutines(d,'2026-09-21');assert.equal(r.tasks.length,5);assert.ok(r.tasks.every(t=>t.due<='2026-09-18'));const paused=recurring();paused.routines[0].active=false;assert.equal(materializeRoutines(paused,today).tasks.length,0);});
