'use client';
import { useCallback,useEffect,useRef,useState,type CSSProperties } from 'react';
import { Activity,ArrowRight,ArrowUpRight,BarChart3,Check,CheckCheck,ChevronRight,Clock3,Cpu,Flame,Flag,Focus,Gem,LayoutDashboard,ListChecks,LoaderCircle,Orbit,Pencil,Plus,RefreshCw,Repeat2,Settings2,ShieldCheck,Sparkles,Target,Trash2,Trophy,Volume2,Zap } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { Gauge,Panel,Blank,Choice,SectionLink } from './ui';
import Editor,{type EditorTarget} from './editor';
import { Reports,Preferences,Catalog } from './insights';
import { type Workspace,type Task,type Category,type Kind,emptyWorkspace,dateKey,formatDate,addDays,percentage,periodTasks,weekDays,streak,achievements,materializeRoutines,removeEntity,workspaceSchema,DAY_NAMES } from '@/lib/jarvis';

type View='overview'|'tasks'|'routines'|'goals'|'competencies'|'reports'|'achievements'|'settings'|'plans';
const nav=[{id:'overview',label:'Visão geral',icon:LayoutDashboard},{id:'tasks',label:'Tarefas',icon:ListChecks},{id:'routines',label:'Rotinas',icon:Repeat2},{id:'goals',label:'Metas',icon:Target},{id:'competencies',label:'Áreas e competências',icon:Focus},{id:'reports',label:'Relatórios',icon:BarChart3},{id:'achievements',label:'Conquistas',icon:Trophy}] as const;
const names:Record<View,string>={overview:'Visão geral',tasks:'Suas tarefas',routines:'Suas rotinas',goals:'Suas metas',competencies:'Áreas e competências',reports:'Relatórios de desempenho',achievements:'Suas conquistas',settings:'Configurações',plans:'Planos e módulos'};
const icons={spark:Sparkles,zap:Zap,flame:Flame,target:Target,flag:Flag,trophy:Trophy};
function Navigation({view,onNavigate,data}:{view:View;onNavigate:(v:View)=>void;data:Workspace}){
 const {setOpenMobile}=useSidebar();const go=(v:View)=>{onNavigate(v);setOpenMobile(false);};
 return <Sidebar className="jarvis-sidebar"><SidebarHeader className="brand"><div className="brand-mark"><Orbit size={32}/></div><div><strong>J.A.R.V.I.S.</strong><span>ASSISTENTE PESSOAL</span></div></SidebarHeader><SidebarContent><p className="nav-caption">CENTRAL DE CONTROLE</p><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>go(n.id)} className="nav-button"><n.icon/><span>{n.label}</span>{n.id==='tasks'&&data.tasks.filter(t=>!t.done).length>0&&<span className="nav-count">{data.tasks.filter(t=>!t.done).length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-separator"/><p className="nav-caption">SISTEMA</p><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="nav-button" isActive={view==='settings'} onClick={()=>go('settings')}><Settings2/><span>Configurações</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton className="nav-button" isActive={view==='plans'} onClick={()=>go('plans')}><Gem/><span>Planos e módulos</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-note"><ShieldCheck size={18}/><span>Seu espaço pessoal<small>Acesso protegido</small></span></div><button className="profile" onClick={()=>go('settings')}><span className="avatar">{data.settings.name.slice(0,2).toUpperCase()}</span><span><strong>{data.settings.name}</strong><small>Meu perfil</small></span><Settings2 size={16}/></button></SidebarFooter></Sidebar>;
}
export default function JarvisApp({initialName}:{initialName:string}){
 const [data,setData]=useState<Workspace>(()=>emptyWorkspace(initialName));const [today,setToday]=useState(dateKey);
 const dataRef=useRef(data),versionRef=useRef(0),savingRef=useRef(false),loadedRef=useRef(false);
 const [loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[sessionExpired,setSessionExpired]=useState(false);
 const [view,setView]=useState<View>('overview'),[editor,setEditor]=useState<EditorTarget|null>(null),[deleting,setDeleting]=useState<{kind:Kind;id:string;title:string}|null>(null);
 const [taskFilter,setTaskFilter]=useState('all'),[areaFilter,setAreaFilter]=useState('all'),[search,setSearch]=useState('');
 const save=useCallback(async(next:Workspace)=>{
  if(savingRef.current||!loadedRef.current)return false;
  const parsed=workspaceSchema.safeParse(next);if(!parsed.success){toast.error(parsed.error.issues[0].message);return false;}
  savingRef.current=true;setBusy(true);setError('');
  try{
   const res=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:versionRef.current,data:parsed.data})});
   const out=await res.json() as {data:Workspace;version:number;error?:string};if(!res.ok){if(res.status===401)setSessionExpired(true);if(res.status===409)setConflict(true);throw new Error(out.error||'Não foi possível salvar.');}
   dataRef.current=out.data;versionRef.current=out.version;setData(out.data);setConflict(false);return true;
  }catch(e){const message=e instanceof Error?e.message:'Falha na conexão. Tente novamente.';setError(message);toast.error(message);return false;}
  finally{savingRef.current=false;setBusy(false);}
 },[]);
 const load=useCallback(async()=>{
  if(savingRef.current)return;setError('');
  try{
   const res=await fetch('/api/workspace',{cache:'no-store'});const out=await res.json() as {data:Workspace;version:number;error?:string};if(!res.ok){if(res.status===401)setSessionExpired(true);throw new Error(out.error||'Não foi possível carregar seus dados.');}setSessionExpired(false);
   dataRef.current=out.data;versionRef.current=out.version;loadedRef.current=true;setData(out.data);setLoaded(true);setConflict(false);
   const day=dateKey();setToday(day);const generated=materializeRoutines(out.data,day);
   if(JSON.stringify(generated)!==JSON.stringify(out.data))await save(generated);
  }catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar seus dados.');}
 },[save]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const tick=()=>{const day=dateKey();if(day!==today&&!savingRef.current){setToday(day);if(loadedRef.current)void save(materializeRoutines(dataRef.current,day));}};const timer=setInterval(tick,60000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[today,save]);
 useEffect(()=>{document.documentElement.dataset.theme=data.settings.theme;document.documentElement.dataset.motion=data.settings.motion?'on':'off';},[data.settings]);
 // Agents can inspect the current, authenticated workspace and open the same task form.
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
  const ctx=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>unknown}}).modelContext;if(!ctx)return;
  const ac=new AbortController();
  const register=(tool:Tool)=>{try{void Promise.resolve(ctx.registerTool(tool,{signal:ac.signal})).catch(()=>{});}catch{/* Enhancement is optional. */}};
  register({name:'read_routine_summary',description:'Read the signed-in person’s saved tasks and completion counts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');if(!loadedRef.current)throw new Error('Data not loaded');const d=dataRef.current;return {tasks:d.tasks.map(t=>({id:t.id,title:t.title,due:t.due,done:t.done})),completed:d.tasks.filter(t=>t.done).length,total:d.tasks.length};}});
  register({name:'start_task_creation',description:'Open the task creation form. Does not create or save a task.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');if(!loadedRef.current||savingRef.current)throw new Error('Workspace unavailable');setEditor({kind:'task'});await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {formOpened:true,saved:false};}});
  return()=>ac.abort();
 },[]);
 const dayTasks=data.tasks.filter(t=>t.due===today),done=dayTasks.filter(t=>t.done).length,overdue=data.tasks.filter(t=>!t.done&&t.due<today),activeGoals=data.goals.filter(g=>!g.done),seq=streak(data,today),allAchievements=achievements(data,today),unlocked=allAchievements.filter(a=>a.current>=a.target).length;
 const editable=loaded&&!busy&&!conflict;
 const open=(kind:Kind,id?:string)=>{if(editable)setEditor({kind,id});};
 const toggleTask=async(t:Task)=>{const d=structuredClone(dataRef.current),task=d.tasks.find(x=>x.id===t.id);if(!task)return;task.done=!task.done;task.completedAt=task.done?today:null;if(await save(d)){toast.success(task.done?'Tarefa concluída. Mais um passo!':'Tarefa reaberta.');if(task.done&&d.settings.audio)speak('Tarefa concluída. Mais um passo na sua evolução.');}};
 const speak=(text:string)=>{if(!('speechSynthesis'in window)){toast.error('Este navegador não oferece leitura em voz.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=1;window.speechSynthesis.speak(u);};
 const next=dayTasks.filter(t=>!t.done).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'))[0]||overdue[0];
 const sortTasks=(items:Task[])=>[...items].sort((a,b)=>Number(a.done)-Number(b.done)||a.due.localeCompare(b.due)||(a.time||'99').localeCompare(b.time||'99'));
 const filtered=sortTasks(data.tasks.filter(t=>(taskFilter==='all'||taskFilter==='today'&&t.due===today||taskFilter==='pending'&&!t.done||taskFilter==='done'&&t.done||taskFilter==='overdue'&&!t.done&&t.due<today)&&(areaFilter==='all'||t.areaId===areaFilter)&&(!search||t.title.toLocaleLowerCase().includes(search.toLocaleLowerCase()))));
 const actions=(kind:Kind,id:string,title:string)=><div className="row-actions"><button aria-label={`Editar ${title}`} disabled={!editable} onClick={()=>open(kind,id)}><Pencil size={15}/></button><button aria-label={`Excluir ${title}`} disabled={!editable} onClick={()=>setDeleting({kind,id,title})}><Trash2 size={15}/></button></div>;
 const taskRows=(items:Task[],isDaily=false)=>items.map(t=>{
  const area=data.areas.find(a=>a.id===t.areaId);return <div className={`task-row ${t.done?'task-done':''}`} key={t.id}><Checkbox checked={t.done} disabled={!editable} onCheckedChange={()=>void toggleTask(t)} aria-label={`${t.done?'Reabrir':'Concluir'} ${t.title}`}/><div className="task-detail"><strong>{t.title}</strong><div className="task-meta">{area&&<span className="area-tag" style={{'--tag-color':area.color} as CSSProperties}>{area.name}</span>}{t.competencyIds.map(id=>data.competencies.find(c=>c.id===id)?.name).filter(Boolean).slice(0,2).map(c=><span key={c}>{c}</span>)}{t.routineId&&<span><Repeat2 size={12}/> Rotina</span>}</div></div><span className={`task-deadline ${!t.done&&t.due<today?'late':''}`}><Clock3 size={13}/>{isDaily?(t.time||'Sem horário'):`${formatDate(t.due)}${t.time?' · '+t.time:''}`}</span><span className={`priority priority-${t.priority}`}>{t.priority==='high'?'Alta':t.priority==='medium'?'Média':'Baixa'}</span>{actions('task',t.id,t.title)}</div>;
 });
 const groupList=(groups:Category[],kind:'area'|'competency',limit?:number)=><div className="group-bars">{groups.slice(0,limit).map(c=>{const tasks=periodTasks(data,addDays(today,-6),today).filter(t=>kind==='area'?t.areaId===c.id:t.competencyIds.includes(c.id));return <div className="group-bar" key={c.id}><div><span><i style={{background:c.color}}/>{c.name}</span><strong>{tasks.length?percentage(tasks)+'%':'—'}</strong></div><Progress value={percentage(tasks)} style={{'--primary':c.color} as CSSProperties}/><small>{tasks.filter(t=>t.done).length} de {tasks.length} tarefas</small></div>;})}</div>;
 return <SidebarProvider style={{'--sidebar-width':'244px'} as CSSProperties}><Navigation view={view} onNavigate={setView} data={data}/><main className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="sidebar-toggle"/><span>Meu espaço</span><ChevronRight size={14}/><strong>{names[view]}</strong></div><div className="topbar-right"><span className="save-state">{busy?<LoaderCircle className="spin" size={14}/>:loaded?<ShieldCheck size={14}/>:<LoaderCircle size={14}/>}<span>{busy?'Salvando':loaded?'Dados sincronizados':'Conectando'}</span></span><span className="topbar-date">{formatDate(today,{day:'numeric',month:'short',year:'numeric'})}</span><span className="small-avatar">{data.settings.name.charAt(0).toUpperCase()}</span></div></header>
 <div className="workspace"><div className="page-heading"><div><p className="eyebrow">J.A.R.V.I.S. / {view==='overview'?'VISÃO DO DIA':names[view].toUpperCase()}</p><h1>{view==='overview'?<>Olá, {data.settings.name.split(' ')[0]}<span className="accent">.</span></>:names[view]}</h1><p>{view==='overview'?'Um novo dia para evoluir. Vamos colocar seus planos em movimento.':view==='tasks'?'Cada pequena ação aproxima você dos seus objetivos.':view==='routines'?'Transforme constância em parte do seu dia.':view==='goals'?'Dê direção aos seus próximos passos.':view==='competencies'?'Conecte o que você faz ao que deseja desenvolver.':view==='reports'?'Sua evolução, a partir das atividades que você registra.':view==='achievements'?'Reconheça cada passo da sua jornada.':view==='settings'?'Deixe seu assistente do seu jeito.':'Conheça as possibilidades de evolução do J.A.R.V.I.S.'}</p></div>{['overview','tasks','routines','goals'].includes(view)&&<Button className="primary-action" disabled={!editable} onClick={()=>open(view==='routines'?'routine':view==='goals'?'goal':'task')}><Plus size={17}/>{view==='routines'?'Nova rotina':view==='goals'?'Nova meta':'Nova tarefa'}</Button>}</div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span>{sessionExpired&&<a href="/login">Entrar novamente</a>}<Button variant="outline" size="sm" onClick={()=>void load()} disabled={busy}>Recarregar dados</Button></div>}
 {data.demo&&<div className="demo-banner"><Sparkles size={16}/>Você está usando dados de demonstração.<button onClick={()=>setView('settings')}>Gerenciar exemplo <ArrowRight size={14}/></button></div>}
 {!loaded&&!error?<div className="loading-grid" aria-label="Carregando sua rotina"><Skeleton className="h-28"/><Skeleton className="h-28"/><Skeleton className="h-80 col-span-2"/></div>:<>
 {view==='overview'&&<>
 <div className="stats-grid"><div className="stat"><span className="stat-icon"><ListChecks/></span><div><span>Tarefas de hoje</span><strong>{done}<small> / {dayTasks.length}</small></strong><p>{dayTasks.length-done} para concluir</p></div><span className="stat-code">01</span></div><div className="stat"><span className="stat-icon purple"><Target/></span><div><span>Metas em andamento</span><strong>{activeGoals.length.toString().padStart(2,'0')}</strong><p>{data.goals.filter(g=>g.done).length} concluídas</p></div><span className="stat-code">02</span></div><div className="stat"><span className="stat-icon amber"><Flame/></span><div><span>Dias de constância</span><strong>{seq.toString().padStart(2,'0')}<small> dias</small></strong><p>Com tarefas concluídas</p></div><span className="stat-code">03</span></div><div className="stat"><span className="stat-icon mint"><Trophy/></span><div><span>Conquistas</span><strong>{unlocked.toString().padStart(2,'0')}<small> / {allAchievements.length}</small></strong><p>Passos que merecem valor</p></div><span className="stat-code">04</span></div></div>
 <div className="overview-grid"><Panel title="Sua evolução começa aqui" eyebrow="NÚCLEO DE DESEMPENHO" className="core-panel" action={<span className="mini-badge">HOJE</span>}><div className="core-body"><div className="core-copy"><div className="tiny-rule"/><h3>Cada ação<br/>faz a <span>diferença.</span></h3><p>{dayTasks.length===0?'Adicione suas tarefas e acompanhe seu progresso ao longo do dia.':done===dayTasks.length?'Você concluiu todas as tarefas de hoje. Reserve um momento para reconhecer seu progresso.':`Você já concluiu ${done} ${done===1?'tarefa':'tarefas'} hoje. Continue no seu ritmo, um passo de cada vez.`}</p><button className="text-link" onClick={()=>setView('reports')}>Ver meu desempenho <ArrowUpRight size={16}/></button></div><Gauge value={percentage(dayTasks)} total={dayTasks.length} done={done}/></div><div className="core-footer"><span><i className="legend-dot"/>{done} concluídas</span><span><i className="legend-dot muted-dot"/>{dayTasks.length-done} pendentes</span><span><i className="legend-dot amber-dot"/>{overdue.length} atrasadas no total</span></div></Panel>
 <Panel title="Vamos focar no próximo passo" eyebrow="SEU ASSISTENTE" className="focus-panel" action={<Cpu size={22}/>}><div className="assistant-wave" aria-hidden="true">{[12,22,15,30,40,20,48,32,18,40,25,15,24,10,18,32,42,22,10].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*.12}s`}}/>)}</div><p>{next?<>Sua próxima tarefa é <strong>{next.title}</strong>. Separe um momento para avançar.</>:dayTasks.length&&done===dayTasks.length?'Você colocou seus planos em ação. Hoje, missão cumprida.':'Estou pronto. Qual é a primeira coisa que você quer realizar hoje?'}</p>{next?<div className="next-task"><span><Clock3 size={14}/>{next.due<today?'Prazo vencido':next.time||'Hoje'}</span><Button variant="outline" disabled={!editable} onClick={()=>void toggleTask(next)}>Concluir tarefa <Check size={16}/></Button></div>:<Button variant="outline" disabled={!editable} onClick={()=>open('task')}>Adicionar tarefa <Plus size={16}/></Button>}<div className="assistant-foot"><span>Resumo baseado na sua rotina</span><button aria-label="Ouvir resumo do dia" onClick={()=>speak(`Olá, ${data.settings.name}. Você concluiu ${done} de ${dayTasks.length} tarefas hoje. ${overdue.length} tarefas estão atrasadas.`)}><Volume2 size={17}/></button></div></Panel>
 <Panel title="Sua agenda de hoje" eyebrow="PLANEJAMENTO" className="agenda-panel" action={<SectionLink onClick={()=>{setTaskFilter('all');setView('tasks');}}>Ver todas</SectionLink>}>{dayTasks.length?<div className="task-list">{taskRows(sortTasks(dayTasks).slice(0,5),true)}{dayTasks.length>5&&<button className="show-more" onClick={()=>{setTaskFilter('today');setView('tasks');}}>Ver as {dayTasks.length} tarefas de hoje <ArrowRight size={15}/></button>}</div>:<Blank title="Seu dia começa com um plano" text="Crie sua primeira tarefa. Cada conclusão vai alimentar seus indicadores." onClick={()=>open('task')} button="Criar primeira tarefa"/>}</Panel>
 <Panel title="Competências em evolução" eyebrow="ÚLTIMOS 7 DIAS" className="competencies-panel" action={<Focus size={20}/>}>{data.competencies.length?groupList(data.competencies,'competency',3):<Blank title="O que você quer desenvolver?" text="Crie competências e associe às suas tarefas."/>}<SectionLink onClick={()=>setView('competencies')}>Explorar competências</SectionLink></Panel>
 <Panel title="Seu ritmo na semana" eyebrow="CONCLUSÃO POR DIA" className="rhythm-panel" action={<span className="subtle">Últimos 7 dias</span>}><div className="week-chart" role="img" aria-label="Percentual de tarefas concluídas por dia">{weekDays(today).map(day=>{const ts=data.tasks.filter(t=>t.due===day),p=percentage(ts);return <div className={`week-day ${day===today?'today':''}`} key={day}><span>{ts.length?p+'%':'—'}</span><div className="bar-track"><i style={{height:p+'%'}}/></div><strong>{day===today?'Hoje':DAY_NAMES[new Date(day+'T12:00:00').getDay()]}</strong><small>{formatDate(day,{day:'2-digit'})}</small></div>;})}</div></Panel>
 <Panel title="Próxima conquista" eyebrow="UM PASSO DE CADA VEZ" className="next-achievement">{(()=>{const a=allAchievements.find(a=>a.current<a.target)||allAchievements[allAchievements.length-1],Icon=icons[a.icon as keyof typeof icons];return <><div className="award-icon"><Icon size={28}/></div><h3>{a.title}</h3><p>{a.description}</p><Progress value={Math.min(100,a.current/a.target*100)}/><div className="award-progress"><span>{Math.min(a.current,a.target)} / {a.target}</span><button onClick={()=>setView('achievements')}>Ver conquistas <ArrowUpRight size={14}/></button></div></>;})()}</Panel>
 </div></>}
 {view==='tasks'&&<Panel className="tasks-panel"><div className="tasks-toolbar"><Tabs value={taskFilter} onValueChange={setTaskFilter}><TabsList>{[{id:'all',label:'Todas'},{id:'today',label:'Hoje'},{id:'pending',label:'Pendentes'},{id:'done',label:'Concluídas'},{id:'overdue',label:'Atrasadas'}].map(x=><TabsTrigger key={x.id} value={x.id}>{x.label}</TabsTrigger>)}</TabsList></Tabs><div className="task-search"><Input aria-label="Buscar tarefas" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar tarefa…"/><Choice label="Filtrar por área" value={areaFilter} onChange={setAreaFilter} options={[{value:'all',label:'Todas as áreas'},...data.areas.map(a=>({value:a.id,label:a.name}))]}/></div></div>{filtered.length?<><div className="list-caption">{filtered.length} {filtered.length===1?'tarefa':'tarefas'} <span>Prazo · Prioridade</span></div>{taskRows(filtered)}</>:<Blank title="Nenhuma tarefa por aqui" text={data.tasks.length?'Tente outro filtro ou crie uma nova tarefa.':'Adicione uma tarefa, defina um prazo e vincule suas competências.'} onClick={()=>open('task')} button="Nova tarefa"/>}</Panel>}
 {view==='routines'&&<><div className="info-strip"><Repeat2 size={18}/><span>Rotinas geram tarefas nos dias escolhidos. Cada ocorrência tem seu próprio status.</span></div><div className="entity-grid">{data.routines.map(r=>{const t=data.tasks.find(t=>t.routineId===r.id&&t.occurrence===today);return <Panel className="entity-card" key={r.id}><div className="entity-top"><span className="entity-icon"><Repeat2/></span><span className={`pill ${r.active?'':'dim'}`}>{r.active?'Ativa':'Pausada'}</span>{actions('routine',r.id,r.title)}</div><h2>{r.title}</h2><p>{r.description||'Uma ação que se repete e constrói constância.'}</p><div className="routine-days">{DAY_NAMES.map((d,i)=><span className={r.days.includes(i)?'on':''} key={d}>{d}</span>)}</div><div className="entity-details"><span><Clock3 size={14}/>{r.time||'Sem horário'}</span><span>Desde {formatDate(r.start)}</span>{r.end&&<span>Até {formatDate(r.end)}</span>}</div><div className="entity-bottom"><Button variant="outline" size="sm" disabled={!editable||!t} onClick={()=>t&&void toggleTask(t)}>{t?.done?<CheckCheck size={16}/>:<Check size={16}/>} {t?t.done?'Concluída hoje':'Concluir hoje':'Sem tarefa hoje'}</Button><Button variant="ghost" size="sm" disabled={!editable} onClick={()=>{const d=structuredClone(data);const x=d.routines.find(x=>x.id===r.id)!;x.active=!x.active;if(x.active)x.lastGenerated=addDays(today,-1);void save(materializeRoutines(d,today));}}>{r.active?'Pausar':'Retomar'}</Button></div></Panel>;})}</div>{!data.routines.length&&<Panel><Blank title="Crie um ritmo que funcione para você" text="Leitura, exercício, estudo: escolha os dias e deixe as tarefas organizadas." button="Criar rotina" onClick={()=>open('routine')}/></Panel>}</>}
 {view==='goals'&&<><div className="entity-grid">{data.goals.map(g=>{const ts=data.tasks.filter(t=>t.goalId===g.id);return <Panel className="entity-card" key={g.id}><div className="entity-top"><span className="entity-icon purple"><Target/></span><span className={`pill ${g.done?'success':''}`}>{g.done?'Concluída':g.due<today?'Prazo vencido':'Em andamento'}</span>{actions('goal',g.id,g.title)}</div><h2>{g.title}</h2><p>{g.description||'Vincule tarefas a esta meta para acompanhar o progresso.'}</p><div className="goal-percent"><span>Tarefas vinculadas</span><strong>{percentage(ts)}%</strong></div><Progress value={percentage(ts)}/><div className="entity-details"><span>{ts.filter(t=>t.done).length} de {ts.length} tarefas</span><span><Clock3 size={14}/>{formatDate(g.due)}</span></div><Button variant={g.done?'outline':'default'} disabled={!editable} onClick={()=>{const d=structuredClone(data);d.goals.find(x=>x.id===g.id)!.done=!g.done;void save(d);}}>{g.done?'Reabrir meta':'Marcar meta como concluída'}</Button></Panel>;})}</div>{!data.goals.length&&<Panel><Blank title="O que você quer alcançar?" text="Defina um objetivo com prazo e conecte as tarefas que ajudam você a chegar lá." onClick={()=>open('goal')} button="Criar meta"/></Panel>}</>}
 {view==='competencies'&&<div className="category-columns">{([{kind:'area',title:'Áreas da sua vida',text:'Agrupe suas atividades por contexto.',list:data.areas},{kind:'competency',title:'Suas competências',text:'Habilidades que você desenvolve na prática.',list:data.competencies}] as const).map(group=><Panel key={group.kind} title={group.title} action={<Button variant="outline" size="sm" disabled={!editable} onClick={()=>open(group.kind)}><Plus size={15}/>{group.kind==='area'?'Nova área':'Nova competência'}</Button>}><p className="section-description">{group.text}</p>{group.list.map(c=>{const ts=data.tasks.filter(t=>group.kind==='area'?t.areaId===c.id:t.competencyIds.includes(c.id));return <div key={c.id} className="category-row"><span className="category-symbol" style={{color:c.color}}><Focus size={22}/></span><div><h3>{c.name}</h3><p>{ts.length} tarefas · {ts.filter(t=>t.done).length} concluídas</p></div><strong style={{color:c.color}}>{ts.length?percentage(ts)+'%':'—'}</strong>{actions(group.kind,c.id,c.name)}</div>;})}{!group.list.length&&<Blank title="Tudo começa com um nome" text="Crie categorias que façam sentido na sua rotina."/>}<p className="help panel-note">Indicadores de todo o histórico. Para escolher um período, abra Relatórios.</p></Panel>)}</div>}
 {view==='reports'&&<Reports data={data} today={today}/>}
 {view==='achievements'&&<><div className="achievement-summary"><div className="award-icon"><Trophy size={32}/></div><div><strong>{unlocked} de {allAchievements.length} conquistas</strong><p>Seu progresso é construído por ações, não por comparação.</p></div></div><div className="achievement-grid">{allAchievements.map(a=>{const unlocked=a.current>=a.target,Icon=icons[a.icon as keyof typeof icons];return <Panel key={a.id} className={`achievement-card ${unlocked?'unlocked':''}`}><span className="achievement-status">{unlocked?'CONQUISTADA':'EM ANDAMENTO'}</span><div className="award-icon"><Icon size={35}/></div><h2>{a.title}</h2><p>{a.description}</p><Progress value={Math.min(100,a.current/a.target*100)}/><span className="achievement-count">{Math.min(a.current,a.target)} / {a.target}</span></Panel>;})}</div><p className="help">Conquistas refletem seus registros atuais. Reabrir ou excluir atividades pode alterar os marcos. Constância conta dias consecutivos com pelo menos uma conclusão.</p></>}
 {view==='settings'&&<Preferences data={data} today={today} save={save} busy={!editable} speak={speak}/>}
 {view==='plans'&&<Catalog/>}
 </>}
 <footer className="workspace-footer"><span><Orbit size={14}/> J.A.R.V.I.S.</span><span>Um passo de cada vez. Uma versão melhor de você.</span><span>PROJETO ACADÊMICO · 2026</span></footer></div></main>
 {editor&&<Editor key={`${editor.kind}-${editor.id||'new'}`} target={editor} data={data} today={today} onClose={()=>setEditor(null)} onSave={save} busy={busy||conflict}/>}
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir “{deleting?.title}”?</AlertDialogTitle><AlertDialogDescription>{deleting?.kind==='task'?'Esta tarefa será removida e deixará de contar nos indicadores.':deleting?.kind==='routine'?'A rotina deixará de gerar tarefas. As tarefas já criadas serão mantidas no histórico.':'Os registros vinculados serão mantidos, sem este vínculo.'} Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction className="danger-button" disabled={busy} onClick={async(e)=>{e.preventDefault();if(deleting&&await save(removeEntity(dataRef.current,deleting.kind,deleting.id))){setDeleting(null);toast.success('Registro excluído.');}}}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Toaster theme="dark" richColors position="bottom-right"/></SidebarProvider>;
}
