'use client';
import { useState,type CSSProperties } from 'react';
import { ArrowUpRight,BarChart3,CheckCircle2,Download,Focus,Gem,Palette,Printer,RotateCcw,ShieldCheck,Sparkles,Volume2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Progress } from '@/components/ui/progress';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { Panel,Choice,Blank } from './ui';
import { parseBackup,BACKUP_FILE_LIMIT } from '@/lib/backup';
import { type Workspace,type Category,percentage,periodTasks,addDays,formatDate,emptyWorkspace,demoWorkspace,CATALOG } from '@/lib/jarvis';
export function Reports({data,today}:{data:Workspace;today:string}){
 const [period,setPeriod]=useState('7'),[fromInput,setFrom]=useState(addDays(today,-6)),[toInput,setTo]=useState(today),[area,setArea]=useState('all'),[competency,setCompetency]=useState('all');
 const quarter=today.slice(0,5)+String(Math.floor((Number(today.slice(5,7))-1)/3)*3+1).padStart(2,'0')+'-01';
 const from=period==='custom'?fromInput:period==='quarter'?quarter:addDays(today,1-Number(period)),to=period==='custom'?toInput:today;
 const valid=!!from&&!!to&&from<=to;
 const tasks=valid?periodTasks(data,from,to).filter(t=>(area==='all'||t.areaId===area)&&(competency==='all'||t.competencyIds.includes(competency))):[];
 const done=tasks.filter(t=>t.done).length;
 const duration=valid?Math.round((Date.parse(to)-Date.parse(from))/86400000)+1:0,step=Math.max(1,Math.ceil(duration/14));
 const buckets=Array.from({length:Math.min(14,Math.ceil(duration/step))},(_,i)=>{const start=addDays(from,i*step),end=addDays(start,step-1),ts=tasks.filter(t=>t.due>=start&&t.due<=end);return {start,end,total:ts.length,done:ts.filter(t=>t.done).length,value:percentage(ts)};});
 const groupTable=(groups:Category[],kind:'area'|'competency')=><Table><TableHeader><TableRow><TableHead>{kind==='area'?'Área':'Competência'}</TableHead><TableHead className="number">Concluídas / total</TableHead><TableHead className="number">Conclusão</TableHead></TableRow></TableHeader><TableBody>{groups.filter(c=>(kind==='area'?area:competency)==='all'||c.id===(kind==='area'?area:competency)).map(c=>{const ts=tasks.filter(t=>kind==='area'?t.areaId===c.id:t.competencyIds.includes(c.id));return <TableRow key={c.id}><TableCell><span className="table-category"><i style={{background:c.color}}/>{c.name}</span></TableCell><TableCell className="number">{ts.filter(t=>t.done).length} / {ts.length}</TableCell><TableCell className="number"><strong style={{color:c.color}}>{ts.length?percentage(ts)+'%':'Sem dados'}</strong></TableCell></TableRow>;})}</TableBody></Table>;
 return <div className="report-print"><div className="report-controls no-print"><Choice label="Período do relatório" value={period} onChange={setPeriod} options={[{value:'7',label:'Últimos 7 dias'},{value:'30',label:'Últimos 30 dias'},{value:'quarter',label:'Trimestre atual'},{value:'custom',label:'Personalizado'}]}/>{period==='custom'&&<><label>De<Input type="date" value={fromInput} onChange={e=>setFrom(e.target.value)}/></label><label>Até<Input type="date" value={toInput} onChange={e=>setTo(e.target.value)}/></label></>}<Choice label="Área do relatório" value={area} onChange={setArea} options={[{value:'all',label:'Todas as áreas'},...data.areas.map(a=>({value:a.id,label:a.name}))]}/><Choice label="Competência do relatório" value={competency} onChange={setCompetency} options={[{value:'all',label:'Todas as competências'},...data.competencies.map(c=>({value:c.id,label:c.name}))]}/><Button variant="outline" disabled={!valid} onClick={()=>window.print()}><Printer size={16}/>Imprimir / PDF</Button></div>
 {!valid?<p className="form-error">Escolha um período válido: a data inicial não pode ser posterior à final.</p>:<><div className="report-heading"><h2>Relatório de desempenho</h2><p>{data.settings.name} · {formatDate(from,{day:'2-digit',month:'2-digit',year:'numeric'})} a {formatDate(to,{day:'2-digit',month:'2-digit',year:'numeric'})}</p><p>{area==='all'?'Todas as áreas':data.areas.find(a=>a.id===area)?.name} · {competency==='all'?'Todas as competências':data.competencies.find(c=>c.id===competency)?.name}{data.demo?' · DADOS DE DEMONSTRAÇÃO':''}</p></div><div className="report-stats"><Panel><span>Total no período</span><strong>{tasks.length}</strong></Panel><Panel><span>Concluídas</span><strong>{done}</strong></Panel><Panel><span>Pendentes</span><strong>{tasks.length-done}</strong></Panel><Panel><span>Taxa de conclusão</span><strong className="accent">{tasks.length?percentage(tasks)+'%':'—'}</strong></Panel></div>
 <Panel title="Evolução no período" eyebrow="TAXA DE CONCLUSÃO">{tasks.length?<div className="report-chart" role="img" aria-label="Percentual de conclusão agrupado por data de prazo">{buckets.map(b=><div className="week-day" key={b.start} title={`${formatDate(b.start)}${step>1?' a '+formatDate(b.end):''}: ${b.done}/${b.total}`}><span>{b.total?b.value+'%':'—'}</span><div className="bar-track"><i style={{height:b.value+'%'}}/></div><small>{formatDate(b.start,{day:'2-digit',month:'2-digit'})}</small></div>)}</div>:<Blank title="Ainda não há dados neste período" text="Registre tarefas ou ajuste o período para acompanhar sua evolução."/>}{step>1&&<p className="help">Cada barra reúne até {step} dias, a partir da data indicada.</p>}</Panel>
 <div className="category-columns report-tables"><Panel title="Desempenho por área">{groupTable(data.areas,'area')}{!data.areas.length&&<p className="help">Nenhuma área cadastrada.</p>}</Panel><Panel title="Desempenho por competência">{groupTable(data.competencies,'competency')}{!data.competencies.length&&<p className="help">Nenhuma competência cadastrada.</p>}</Panel></div>
 <Panel className="report-method"><BarChart3 size={20}/><div><h3>Como seu resultado é calculado</h3><p>Percentual = tarefas concluídas ÷ total de tarefas do grupo no período × 100. O período usa a data de prazo da tarefa; a conclusão considera o status atual. Sem tarefas, o resultado é “Sem dados”. Os valores são arredondados ao inteiro mais próximo.</p><p>Uma tarefa pode contribuir para mais de uma competência. Tarefas sem área ou competência entram no total geral, mas não em um grupo. O indicador descreve os registros de execução, não mede sua capacidade pessoal.</p></div></Panel></>}
 </div>;
}
export function Preferences({data,today,save,busy,speak}:{data:Workspace;today:string;save:(d:Workspace)=>Promise<boolean>;busy:boolean;speak:(s:string)=>void}){
 const [name,setName]=useState(data.settings.name),[confirm,setConfirm]=useState<'demo'|'reset'|null>(null);
 const [pendingImport,setPendingImport]=useState<Workspace|null>(null);
 async function chooseBackup(file:File|undefined){if(!file)return;try{if(file.size>BACKUP_FILE_LIMIT)throw new Error('O arquivo deve ter até 8 MB.');setPendingImport(parseBackup(await file.text()));}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível ler o arquivo.');}}
 async function setting<K extends keyof Workspace['settings']>(key:K,value:Workspace['settings'][K]){const d=structuredClone(data);d.settings[key]=value;if(await save(d))toast.success('Preferência salva.');}
 const empty=data.tasks.length===0&&data.routines.length===0&&data.goals.length===0;
 return <div className="settings-grid"><Panel title="Seu perfil" eyebrow="IDENTIDADE"><form onSubmit={e=>{e.preventDefault();void setting('name',name.trim());}} className="profile-form"><label>Como você quer ser chamado?<Input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><Button disabled={busy||!name.trim()}>Salvar nome</Button></form><p className="help">Seus registros pertencem à conta com a qual você acessa este espaço.</p><form action="/auth/logout" method="post" className="logout-form"><Button variant="outline" disabled={busy}>Sair da conta</Button></form></Panel>
 <Panel title="Interface e movimento" eyebrow="PERSONALIZAÇÃO" action={<Palette size={20}/>}><p className="section-description">Escolha a cor dos indicadores e controles.</p><div className="theme-picker">{[{id:'cyan',name:'Reator azul',color:'#55dcf7'},{id:'blue',name:'Órbita violeta',color:'#b3a2ff'},{id:'amber',name:'Energia âmbar',color:'#f3c47b'}].map(t=><button key={t.id} disabled={busy} className={data.settings.theme===t.id?'selected':''} onClick={()=>void setting('theme',t.id as Workspace['settings']['theme'])}><span style={{background:t.color}}/>{t.name}{data.settings.theme===t.id&&<CheckCircle2 size={15}/>}</button>)}</div><div className="setting-row"><label htmlFor="motion">Animações suaves<small>Respeita a preferência de movimento do seu dispositivo.</small></label><Switch id="motion" checked={data.settings.motion} disabled={busy} onCheckedChange={v=>void setting('motion',v)}/></div></Panel>
 <Panel title="Respostas em áudio" eyebrow="VOZ DO ASSISTENTE" action={<Volume2 size={20}/>}><div className="setting-row"><label htmlFor="audio">Ouvir ao concluir uma tarefa<small>Leitura em português pela voz disponível no navegador.</small></label><Switch id="audio" checked={data.settings.audio} disabled={busy} onCheckedChange={v=>void setting('audio',v)}/></div><Button variant="outline" onClick={()=>speak(`Olá, ${data.settings.name}. Estou pronto para acompanhar sua rotina.`)}><Volume2 size={16}/>Testar voz</Button><p className="help">A disponibilidade depende do navegador. Não há conversa por voz nem IA generativa integrada.</p></Panel>
 <Panel title="Seus dados" eyebrow="CONTINUIDADE" action={<ShieldCheck size={20}/>}><p>Suas alterações são salvas automaticamente após cada ação. Você pode guardar uma cópia dos seus registros.</p><Button variant="outline" disabled={busy} onClick={()=>{const blob=new Blob([JSON.stringify({application:'JARVIS',schemaVersion:1,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`jarvis-dados-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success('Cópia preparada.');}}><Download size={16}/>Exportar meus dados</Button><p className="help">Esta exportação manual não é o serviço de backup automático ou recuperação avançada previsto no catálogo.</p><label className="backup-import">Importar dados de outra instalação<Input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{void chooseBackup(e.target.files?.[0]);e.target.value='';}}/><span className="help">Selecione a cópia exportada pelo JARVIS. Você poderá conferir antes de substituir seus registros.</span></label></Panel>
 <Panel title="Demonstração acadêmica" eyebrow="EXPERIMENTE OS INDICADORES" className="demo-settings"><div><p>Um cenário com 10 tarefas, sendo 8 concluídas, permite verificar o indicador de <strong>80%</strong> da competência Disciplina, conforme o exemplo do projeto.</p><p className="help">O exemplo só pode ser carregado em um espaço sem tarefas, metas e rotinas. Dados de demonstração são sempre identificados.</p></div><Button variant="outline" disabled={busy||(!empty&&!data.demo)} onClick={()=>setConfirm(data.demo?'reset':'demo')}>{data.demo?<RotateCcw size={16}/>:<Sparkles size={16}/>} {data.demo?'Limpar demonstração':'Carregar demonstração'}</Button></Panel>
 <div className="settings-note"><Gem size={20}/><p><strong>Acesso acadêmico.</strong> O protótipo libera seus recursos implementados para avaliação. Os planos, limites comerciais e serviços do catálogo ainda não são cobrados nem contratados.</p></div>
 <AlertDialog open={!!pendingImport} onOpenChange={v=>{if(!v&&!busy)setPendingImport(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Importar seus registros?</AlertDialogTitle><AlertDialogDescription>O arquivo contém {pendingImport?.tasks.length} tarefas, {pendingImport?.routines.length} rotinas, {pendingImport?.goals.length} metas, {pendingImport?.areas.length} áreas e {pendingImport?.competencies.length} competências. A importação substitui todos os registros e preferências desta conta. Exporte os dados atuais antes de continuar se quiser guardá-los. A instalação de origem não será alterada.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(pendingImport&&await save(pendingImport)){setName(pendingImport.settings.name);setPendingImport(null);toast.success('Dados importados e salvos.');}}}>Importar e substituir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm==='demo'?'Carregar dados de demonstração?':'Limpar o espaço de demonstração?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='demo'?'Serão adicionadas 10 tarefas e uma meta de exemplo, com áreas e competências do cenário de teste. Suas preferências serão mantidas.':'Todas as tarefas, rotinas, metas, áreas e competências deste espaço de demonstração serão substituídas pelos cadastros iniciais. Isso inclui alterações feitas após carregar o exemplo. Exporte seus dados antes, se quiser guardá-los.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();const d=confirm==='demo'?demoWorkspace(data.settings.name,today):emptyWorkspace(data.settings.name);d.settings={...data.settings};if(await save(d)){setConfirm(null);toast.success(confirm==='demo'?'Demonstração carregada.':'Espaço pronto para sua rotina.');}}}>Confirmar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
export function Catalog(){
 const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="catalog"><div className="catalog-note"><Gem size={23}/><div><strong>Modelo comercial do projeto</strong><p>Catálogo previsto no PCC. As contratações ainda não estão disponíveis. O acesso atual é acadêmico, sem cobrança.</p></div></div><div className="plan-cards">{CATALOG.slice(0,3).map(([title,description,price],i)=><Panel key={title} className={`plan-card ${i===1?'featured':''}`}><span className="eyebrow">{i===0?'O PRIMEIRO PASSO':i===1?'EVOLUÇÃO CONTÍNUA':'UM ANO DE POSSIBILIDADES'}</span><h2>{title.replace('Plano ','')}</h2><strong className="price">{money(price)}</strong><span className="price-period">{i===1?'por mês':i===2?'pagamento anual':'acesso básico'}</span><p>{description}</p><span className="planned-badge">{i===0?'Limite comercial: 3 competências':'Oferta planejada'}</span></Panel>)}</div>
 <Panel title="Módulos, licenças e serviços" eyebrow="CATÁLOGO COMPLETO"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Produto / serviço</TableHead><TableHead>Tipo</TableHead><TableHead className="number">Valor</TableHead></TableRow></TableHeader><TableBody>{CATALOG.map(([title,description,price,type],i)=><TableRow key={title}><TableCell className="catalog-code">{String(i+1).padStart(3,'0')}</TableCell><TableCell><strong>{title}</strong><p className="table-description">{description}</p></TableCell><TableCell><span className="catalog-type">{type}</span></TableCell><TableCell className="number catalog-price">{money(price)}</TableCell></TableRow>)}</TableBody></Table></Panel>
 <Panel title="O que já está disponível" className="scope-note"><div><CheckCircle2 size={20}/><p>Tarefas, rotinas recorrentes, metas, áreas, competências, relatórios, conquistas, temas, leitura de voz do navegador e exportação/importação manual de dados.</p></div><div><Focus size={20}/><p><strong>Expansões previstas:</strong> IA avançada, sincronização com Google Calendar e Outlook, backup automático privado, API externa, recursos corporativos, finanças e metodologias. Consultoria, análise profissional, suporte 24/7 e treinamento dependem de uma operação de serviços.</p></div><p className="help">Preços e descrições preservados da tabela da seção 2.5 do PCC. Os recursos futuros seguem as limitações descritas na seção 3.2.</p></Panel></div>;
}
